export const colors = {
  skyBlue: '#069ccd',
  whiteGray: '#f7f6f3',
  dusk: 'rgb(65,77,107)',
  green: 'rgb(29,211,168)',
  greenBlue: 'rgb(36,205,151)',
  mediumGray: 'rgb(134,154,183)',
  paleGray: 'rgb(221,226,236)',
  lightBackground: 'white',
  lightBackgroundLight: '#f7f6f3',

  black: '#323C47',
  gray: '#707683',
  primary: '#609FFF',
  secondary: '#A055FF',
  light: '#ffffff',
  dark: '#1B1B21',
  lightGray: '#E5E5E5',
  blue: '#6DA6FC',
  google: '#E04238',
  facebook: '#345997',

  /** Temporary dooboo Theme */
  white4: 'rgba(255, 255, 255, 0.1)',
  white3: 'rgba(237, 237, 237, 0.2)',
  white2: 'rgba(255, 255, 255, 0.3)',
  white1: 'rgba(255, 255, 255, 0.7)',
  white0: 'rgba(255, 255, 255, 0.6)',
  primary9: '#506FD6',
  primary8: '#5f88ea',
  primary7: '#6397F9',
  primary6: '#6DA6FC',
  primary5: '#76B1FF',
  primary4: '#9AC7FF',
  primary3: '#A1CBFF',
  primary2: '#c4dfff',
  primary1: '#e6f2ff',
  dark7: '#1B1B21',
  dark6: '#1E1E1E',
  dark5: '#252525',
  dark4: '#272727',
  dark3: '#2F2F2F',
  dark2: '#353535',
  dark1: '#383838',
  gray9: '#4F4F4F',
  gray8: '#323C47',
  gray7: '#707683',
  gray6: '#90A0B7',
  gray5: '#CBD7E5',
  gray4: '#BDBDBD',
  gray3: '#F2F2F2',
  gray2: '#E0E0E0',
  gray1: '#ECF0F5',
  gray0: '#E5E5E5',
  red4: '#D84910',
  red3: '#DD4B39',
  red2: '#DE5250',
  red1: '#E54E4E',
  red0: '#FCEDE8',
  green1: '#009C36',
  green0: '#E7FAEB',
  blue2: '#3B5998',
  blue1: '#609FFF',
  blue0: '#109CF1',
};

export const light = {
  isBlack: true,
  mainBackground: colors.lightGray,
  primary: colors.primary,
  secondary: colors.secondary,
  logo: colors.primary,
  headerBackground: 'black',
  drawerBackground: '#f8f8f8',
  drawerItemBorder: '#e6e6e6',
  drawerItemLabel: '#555',
  overlay: colors.dark,
  overlayFont: 'white',
  overlayForm: 'rgba(255, 255, 255, 0.1)',
  overlayFormBorder: 'rgba(255, 255, 255, 0.3)',
  background: colors.lightBackground,
  btnPrimaryBorder: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: 'white',
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  font: colors.dark,
  tint: '#333333',
  title: colors.black,
  btnBlue: colors.blue,
  boxShadow: 'rgba(144, 160, 183, 0.15)',
  grayFont: colors.gray,
  contentShadow: '#ecf0f5',
  content: 'white',
  facebookIcon: colors.light,
  facebookText: colors.light,
  facebookBackground: colors.facebook,
  googleIcon: colors.light,
  googleText: colors.light,
  googleBackground: colors.google,
  /** doobooTheme */
  layout: colors.gray0,
  btnPrimary: colors.primary6,
  btnGoogle: colors.red2,
  btnFacebook: colors.blue2,
  btnFont: '#FFFFFF',
  btnGray: colors.gray5,
  btnWhite: '#ffffff',
  text: colors.gray8,
  whiteText: '#ffffff',
  blueText: colors.blue1,
  darkText: colors.dark7,
  grayText: colors.gray7,
  line: colors.gray1,
  darkLine: colors.gray6,
  thickLine: colors.primary6,
  mediumLine: colors.primary8,
  border: '#EDEDED',
  borderLight0: colors.gray1,
  borderLight1: colors.gray2,
  borderLight2: colors.gray4,
  borderLight3: colors.gray5,
  disableColor: colors.white3,
  lightBlueBackground: colors.primary1,
  warnBackground: colors.red0,
  warnColor: colors.red4,
  tealBackGround: colors.green0,
  tealColor: colors.green1,
  whiteBackground: '#FFFFFF',
  whiteDark1: '#FFFFFF',
  whiteDark2: '#FFFFFF',
  white: '#FFFFFF',
  white1: colors.white1,
  white2: colors.white2,
  white4: colors.white4,

  gray: colors.gray,
  primary7: colors.primary7,
  avator: colors.gray5,
  notification: colors.gray,
};

export type Theme = typeof light;

export const dark: Theme = {
  isBlack: false,
  mainBackground: colors.dark,
  primary: colors.primary,
  secondary: colors.secondary,
  logo: '#76B1FF',
  headerBackground: 'black',
  drawerBackground: '#f8f8f8',
  drawerItemBorder: '#e6e6e6',
  drawerItemLabel: '#555',
  overlay: colors.dark,
  overlayFont: 'white',
  overlayForm: 'rgba(255, 255, 255, 0.1)',
  overlayFormBorder: 'rgba(255, 255, 255, 0.3)',
  background: colors.dark,
  btnPrimaryBorder: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: colors.whiteGray,
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  font: 'white',
  tint: '#a3a3a3',
  title: 'white',
  btnBlue: colors.dark,
  boxShadow: 'rgba(144, 160, 183, 0.15)',
  grayFont: colors.gray,
  contentShadow: '#ecf0f5',
  content: 'black',
  facebookIcon: colors.light,
  facebookText: colors.light,
  facebookBackground: colors.facebook,
  googleIcon: colors.light,
  googleText: colors.light,
  googleBackground: colors.google,
  /** doobooTheme */
  layout: colors.dark6,
  btnPrimary: colors.primary5,
  btnGoogle: colors.red2,
  btnFont: colors.dark6,
  btnFacebook: colors.primary9,
  btnGray: colors.dark1,
  btnWhite: colors.dark1,
  text: colors.white1,
  whiteText: colors.white1,
  blueText: colors.primary5,
  darkText: colors.white1,
  grayText: colors.white1,
  line: colors.white1,
  darkLine: colors.gray5,
  thickLine: colors.primary5,
  mediumLine: colors.primary8,
  border: '#E0E0E0',
  borderLight0: colors.gray1,
  borderLight1: colors.white0,
  borderLight2: colors.gray4,
  borderLight3: colors.gray5,
  disableColor: colors.white3,
  lightBlueBackground: colors.primary1,
  warnBackground: colors.red0,
  warnColor: colors.red4,
  tealBackGround: colors.green0,
  tealColor: colors.green1,
  whiteBackground: colors.dark6,
  whiteDark1: colors.dark1,
  whiteDark2: colors.dark2,
  white: '#FFFFFF',
  white1: colors.white1,
  white2: colors.white2,
  white4: colors.white4,

  gray: colors.gray,
  primary7: colors.primary7,
  avator: colors.gray5,
  notification: colors.white1,
};
