export const colors = {
  skyBlue: '#069ccd',
  whiteGray: '#f7f6f3',
  dusk: 'rgb(65,77,107)',
  green: 'rgb(29,211,168)',
  greenBlue: 'rgb(36,205,151)',
  mediumGray: 'rgb(134,154,183)',
  paleGray: 'rgb(221,226,236)',
  lightBackground: 'white',
  lightBackgroundLight: '#f7f6f3',

  black: '#323C47',
  gray: '#707683',
  primary: '#609FFF',
  secondary: '#A055FF',
  light: '#ffffff',
  dark: '#1B1B21',
  lightGray: '#E5E5E5',
  blue: '#6DA6FC',
  google: '#E04238',
  facebook: '#345997',
};

export const light = {
  isBlack: true,
  mainBackground: colors.lightGray,
  primary: colors.primary,
  secondary: colors.secondary,
  logo: colors.primary,
  headerBackground: 'black',
  drawerBackground: '#f8f8f8',
  drawerItemBorder: '#e6e6e6',
  drawerItemLabel: '#555',
  overlay: colors.dark,
  overlayFont: 'white',
  overlayForm: 'rgba(255, 255, 255, 0.1)',
  overlayFormBorder: 'rgba(255, 255, 255, 0.3)',
  background: colors.lightBackground,
  btnPrimary: colors.primary,
  btnPrimaryBorder: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: 'white',
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  font: colors.dark,
  tint: '#333333',
  title: colors.black,
  btnBlue: colors.blue,
  boxShadow: 'rgba(144, 160, 183, 0.15)',
  grayFont: colors.gray,
  contentShadow: '#ecf0f5',
  content: 'white',
  facebookIcon: colors.light,
  facebookText: colors.light,
  facebookBackground: colors.facebook,
  googleIcon: colors.light,
  googleText: colors.light,
  googleBackground: colors.google,
};

export type Theme = typeof light;

export const dark: Theme = {
  isBlack: false,
  mainBackground: colors.dark,
  primary: colors.primary,
  secondary: colors.secondary,
  logo: '#76B1FF',
  headerBackground: 'black',
  drawerBackground: '#f8f8f8',
  drawerItemBorder: '#e6e6e6',
  drawerItemLabel: '#555',
  overlay: colors.dark,
  overlayFont: 'white',
  overlayForm: 'rgba(255, 255, 255, 0.1)',
  overlayFormBorder: 'rgba(255, 255, 255, 0.3)',
  background: colors.dark,
  btnPrimary: colors.primary,
  btnPrimaryBorder: colors.skyBlue,
  btnPrimaryFont: 'white',
  btnPrimaryLight: colors.whiteGray,
  btnPrimaryLightFont: 'black',
  textDisabled: '#969696',
  btnDisabled: 'rgb(224,224,224)',
  font: 'white',
  tint: '#a3a3a3',
  title: 'white',
  btnBlue: colors.dark,
  boxShadow: 'rgba(144, 160, 183, 0.15)',
  grayFont: colors.gray,
  contentShadow: '#ecf0f5',
  content: 'black',
  facebookIcon: colors.light,
  facebookText: colors.light,
  facebookBackground: colors.facebook,
  googleIcon: colors.light,
  googleText: colors.light,
  googleBackground: colors.google,
};
